### ISSUE TITLE
Admob Open Bidding/ Facebook Realm Time Bidding

### ISSUE THREAD

**Issue by tfkci** [ammarahm-ed/react-native-admob-native-ads#171]
Facebook says they will only support real-time bidding for their platform soon. On the other hand, I couldn't succeed to have the impression from Facebook for bidding auction type while I have from classical waterfall mediation setup with this library.

When I implemented initialization to the application class, it started making requests while not showing ads.  Admob Open Bidding system works like charm though.

Is this library support real-time bidding for FB?  Should I do anything besides the Google Documentation to enable it?

**Comment by ammarahm-ed** [comment]
@tfkci Maybe that is because we are using older version of google mobile ads library and we can't update to newer version because it will cause incompatibility with other ad libraries that are not updated.

You can test out https://github.com/ammarahm-ed/react-native-admob-native-ads/tree/googleads-8.0.0 branch and see if changes anything for you.
