### ISSUE TITLE
European User Consent

### ISSUE THREAD

**Issue by perrosnk** [ammarahm-ed/react-native-admob-native-ads#24]
Under the Google EU User Consent Policy, you must make certain disclosures to your users in the European Economic Area (EEA) and obtain their consent to use cookies or other local storage, where legally required, and to use personal data (such as AdID) to serve ads. This policy reflects the requirements of the EU ePrivacy Directive and the General Data Protection Regulation (GDPR).

React-native-firebase has implemented a [way](https://rnfirebase.io/admob/european-user-consent) of doing this.

Is there a way to integrate this library with react-native-firebase or find another of implementing the user consent?

**Comment by ammarahm-ed** [comment]
I think you could use something like this here: https://www.npmjs.com/package/react-native-ad-consent

**Comment by hannesschmidt** [comment]
I don't think that this will be enough. Even though you can get the consent and update the status accordingly, there is currently no way of forwarding the status of consent to this library, so that the actual ad request receives the status. 

Could you implement a simple personalized/non-personalized prop to the NativeAdView component? I think this can easily be achieved by simply adding a URL parameter to the request.

From the React Native Firebase SDK: 

> The requested ad URL via the SDK will send a request with an additional parameter &npa=1, which will return a non-personalized ad.

**Comment by ammarahm-ed** [comment]
@hannesschmidt that could be done possibly, I will look into it very soon

**Comment by KVinS** [comment]
This option is very important for applications from Google Family.

**Comment by ammarahm-ed** [comment]
This will be added in the next release

**Comment by ammarahm-ed** [comment]
this is added for **v0.3.0**
