### ISSUE TITLE
Override Pressing Action

### ISSUE THREAD

**Issue by enaluz** [ammarahm-ed/react-native-admob-native-ads#25]
Awesome work on this library @ammarahm-ed! I was looking for a library just like this one recently, and this was super convenient. I can think of a bunch of other features that would be great additions. I'm happy to help where I can. 

**My Ask:**
I'm trying to override the link redirect that happens when the `<NativeAdView/>` component is pressed (assuming this component is responsible for handling the "press" action). I'd like to open the link in WebView rather than redirect the user off of the app. I was reading the code at the native iOS layer and the JS layer, but couldn't figure out how to override that behavior.

Any ideas?

P.S. I'm coming from a Typescript background, and noticed there were some improvements that can be made with the `index.d.ts` file. For now, I just patched my local version of the file using [`patch-package`](https://github.com/ds300/patch-package), but I'm happy to make a PR if that's welcome. 

Thanks!

**Comment by ammarahm-ed** [comment]
@enaluz That is a great idea and would have been very convenient for the user however I have found no way to control where the ad will open since all the click events etc on the ad are handled by the `UnifiedNativeAdView`. And even if in some way we could do that, the other problem would be that the clicks won't be registered by Admob server so we are kind of stuck here. However I will check If it is possible.

Also I would be happy to see some contributions haha so **send in a PR**. Btw have you seen it somewhere? Admob ads opening without leaving the app?
