### ISSUE TITLE
Can't use with typescript

### ISSUE THREAD

**Issue by andresd** [ammarahm-ed/react-native-admob-native-ads#42]
When I want to use a NativeAdView in a component inside a tsx file, I get the error: "'NativeAdView' cannot be used as a JSX component". if I convert the tsx to js then it works fine.

**Comment by andresd** [comment]
same error also in jsx files...

**Comment by ammarahm-ed** [comment]
No idea how to fix it since i only use .js files in my projects. You can look at the `index.d.ts` file and see what might be the issue. The components are not written in typescript, I have only added a declaration file which works well with javascript. No idea about typescript. If you know how to fix, PR is welcome

**Comment by ammarahm-ed** [comment]
Fix in version **v0.3.5**
