### ISSUE TITLE
How is the height decided?

### ISSUE THREAD

**Issue by Veid** [ammarahm-ed/react-native-admob-native-ads#6]
Hi,

How is the height of the ad unit determined? If I place the unit in a `View` with `flex:1`, the unit is shifted such that the top of the `View` is aligned with the **middle** of the unit. The result is the unit overflowing out of the top of its parent `View`, which is a problem.

Am I missing something? Should we set a constant height on the parent `View`? How should we pick the correct height value?

Thanks for your work on this library, it looks promising.
Cheers!

**Comment by ammarahm-ed** [comment]
Hi there, since all the views are generated from .xml and .xib files, the height is fixed for them. For the large size ad, its 420 i guess. and for small, it is 120 and for medium on android it is 200. However in a week or so, if things go right I will release a new version that will work similar to react-native-fbads and you can actually create whatever you want from the components so hang on tight.

**Comment by Veid** [comment]
Very cool, looking forward to checking out the new version. Thanks!
