### ISSUE TITLE
Support MediaAspectRatio

### ISSUE THREAD

**Issue by henrik-d** [ammarahm-ed/react-native-admob-native-ads#64]
I have an image in my native ad. I would prefer to get landscape images only, because the ads become very large otherwise.

Could you add support for [setMediaAspectRatio()](https://developers.google.com/admob/android/native/options)?

**Comment by mrousavy** [comment]
I second this! Only need square ads in my case

**Comment by ammarahm-ed** [comment]
That could be added!

**Comment by henrik-d** [comment]
@ammarahm-ed Any plans to support this soon?

**Comment by ammarahm-ed** [comment]
@henrik-d will come in the next major release

**Comment by cokepizza** [comment]
I only need a four square (non-rectangular) ad.

https://developers.google.com/admob/android/native/options?hl=en
https://support.google.com/admanager/answer/7031536?hl=en

Looking at the guidelines for native ads, it seems that aspect ratio can be set to 1:1, but this library does not seem to provide such a function yet.

Maybe because I'm using the test unit id, it doesn't mean that there is a problem, right?
I would appreciate it if you put this feature in the next release.
Could you please let me know when the next release will be available?

**Comment by ammarahm-ed** [comment]
support added.
