### ISSUE TITLE
Ads not loading! Possibility to add async loader?

### ISSUE THREAD

**Issue by mrousavy** [ammarahm-ed/react-native-admob-native-ads#71]
Hi! 

The ads are really slow on load times, and sometimes don't load at all! So my box appears blank.

The problem only is, I cannot hide my ads until they are loaded. I have to display an ugly white box which is empty for some time. I would really appreciate a somewhat not declarative way of loading ads, so instead of just rendering a `<NativeAd` in JSX, I would like a function I can call, like this:

```js
// pass some parameters like config, options, etc
const ad = await AdManager.loadAd( ... );
```

With this I have **way** more control over ads, I can delay loading them, I can load them only on WiFi, I can pre-load them, etc.

Then, I can just render that ad.

Either manually:

```tsx
// custom hook approach
const ad = useAd();
// ..

return <View> <Text> {ad.title} </Text> </View>;
```
or if that's not possible, just using the default ad view:

```tsx
// custom hook approach
const ad = useAd();
// ..

return <NativeAd ad={ad}> <MediaView ... /> </NativeAd>;
```

This would be a way better approach, since currently I have no control over ad loading and just _assume_ that they load successfully at some point.

Also, I can't hide my ads if they failed to load, because the **onLoadFailed** event fires way too early! So if I were to hide my ad (e.g. by returning `null` in my view) when the ad failed to load, the ad doesn't re-load anymore since the view isn't there. you see the problem?

<img src="https://user-images.githubusercontent.com/15199031/91717672-3ed32900-eb92-11ea-9609-a45f328ceb48.jpeg" width="50%">

**Comment by mrousavy** [comment]
With the second approach, we can still use the React Context you were talking about in https://github.com/ammarahm-ed/react-native-admob-native-ads/issues/9#issuecomment-677016109 and just let it use the ad we supply via the `<NativeAd ad=` property.

**Comment by ammarahm-ed** [comment]
The only way to properly fix the issue is implementing Ad Preloading in native code. Let's say we get 5 ads on app load, where ever you navigate or move, ads are always present for x amount of time. The feature is partially implemented on Android in a separate branch. [ad-preloading-patch](https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/ad-preloading-patch) It still loads the ad on the native side, stores it as a static value, the good thing is even if you reload the app, or refresh JS etc, your ads will persist between navigating etc. But its incomplete yet. Thats the only reliable way to fix the issue of ads failing to load or taking too much time. 

Since I have noticed most of the times the same ads are loaded from the server, if they are preloaded we can save a ton of bandwidth too probably.

The current implementation is such that if the ad fails to load, the view should hide itself. We cannot populate the views later on, especially the MediaView which needs to be present and visible before the ad is loaded otherwise it is not populated with media content i.e image or video both and stays blank. 

But I think it needs more refinement and testing to handle all the cases. If you look into this [line](https://github.com/ammarahm-ed/react-native-admob-native-ads/blob/0742c6aa0cbf43b1c20be32142cfd74b4ea75507/src/index.js#L127) you can see that when the `nativeAd` is null, the view should hide itself, it is still there but only hidden. Maybe that needs to be more optimized. Maybe when the ad fails to load we need to set the `nativeAd` to null.

**Comment by ammarahm-ed** [comment]
On Preloading ads: This will also fix the issue of low impressions and high number of ad requests since it is highly likely that the user might navigate away from the screen before the ad is shown(but is loaded till then) hence impressions are not recorded. @mrousavy

**Comment by bhavikgajera92** [comment]
Good Morning @ammarahm-ed 

When I tried to run the native video ads. By default it is coming muted. In Android we fixed it but in iOS we are not able to find it. Can you please tell us what is the possible workaround for that ?

I tried by editing in RNGADNativeView.m
[GADMobileAds sharedInstance].applicationMuted = No
But it returned with error: property ‘applicationMuted’ not found on object of type ‘GADRequestConfiguration *’

Please help. Thanks in advance.
